Add files via upload
COP4331C-Project-Group/PersonalContactManager pull request #22
Opened 2022-09-06 14:51 UTC by Shrewstar

#13

2022-09-06 20:13 UTC, nashirj requested changes
Overall looks great, ty. Can you also add something to the README about how to use this script to initialize the database and about how to clear the values if you want to reset the database state? Thank you for doing this.

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +PRIMARY KEY (ID),
Please add indentation here to make it easier to read.

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +CREATE DATABASE COP4331;
`CREATE DATABASE IF NOT EXISTS COP4331;`

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +CREATE TABLE User (
`CREATE TABLE IF NOT EXISTS User`

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +USE COP4331;
Newline here please

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +CREATE TABLE Contacts (
Newline here please

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +CREATE TABLE Contacts (
`CREATE TABLE IF NOT EXISTS Contacts`

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +FOREIGN KEY (UserID) REFERENCES Users(ID)
Please indent

2022-09-06 20:13 UTC, nashirj commented on CreateTables.sql
> +) ENGINE = InnoDB;
Newline here please

2022-09-09 11:38 UTC, mplekunov approved these changes
Good Job! LGTM

2022-09-09 11:40 UTC, merged